language: ruby
rvm:
  - 2.5
cache: bundler
before_install:
  - gem update --system # Upgrade RubyGems
  - openssl aes-256-cbc -K $encrypted_18890b4bd683_key -iv $encrypted_18890b4bd683_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
  - rm -rf .bundle/ # Remove bundler config. Don't use it on CI.
script:
  - bundle exec rubocop
  - bundle exec rake
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
